### ISSUE TITLE
rename negative syntax tests to .err.

### ISSUE THREAD

**Issue by ericprud** [w3c/rdf-tests#10]
http://www.w3.org/2013/TurtleTests/turtle-syntax-bad-*.ttl

They aren't really turtle files, which becomes clear when you try to look at them in a browser which cares about that stuff, c.f. <http://www.w3.org/mid/20150719141712.GA9165@w3.org>

**Comment by afs** [comment]
Alternative: keep the naming (for systems that depend on file extension to pick the parser) and use web server configuration to serve them as plain/text.

At the very least ".err" is bland (error of what?) - suggestion: ".ttl-err" or no extension or ".txt".

**Comment by dydra** [comment]
is their purpose not to test the control/data flow in an implementation when it is presented with a file which purports to be turtle but is not?
in which case both the name and the served media type should be "as if".

**Comment by ansell** [comment]
I agree with @dydra, their purpose is to see what happens when a file is self-identified as Turtle and it is attempted to be parsed by a Turtle parser, but it has errors. The test manifest clearly identifies the files as invalid syntax/semantics and that should be enough.

If the file extensions are changed, it may not make a difference to most test harnesses where the use of a Turtle parser implementation is likely hardcoded into their test harness. However, it doesn't self-identify the file as Turtle, so it could fail too early if the test harness does not pick up that it needs to even enter the Turtle parser, failing instead at a higher level such as the parser selection stage. 

It is important that these false positive test cases actually enter the Turtle parser, and if they are tightly constrained they will test a single specific failure case, which wouldn't occur if the parser was never entered due to issues with self-identification of the file using its file extension.

**Comment by gkellogg** [comment]
I agree that the extension should remain .ttl. Note that using gh-pages, we have no control over mime-time, but it correctly uses text/turtle for .ttl files. The tests already have "-bad-" in them, so it's easy to tell visually which ones are expected to be invalid Turtle (same for other formats). Perhaps @ericprud can give some background for this.

**Comment by ericprud** [comment]
I am quite convinced by the arguments to use .ttl.

**Comment by gkellogg** [comment]
Closing without change.
