### ISSUE TITLE
Test case subquery02

### ISSUE THREAD

**Issue by nkaralis** [w3c/rdf-tests#150]
Hello.

I have a question about the test case [subquery02](https://github.com/w3c/rdf-tests/blob/12a81bbafc522850ae5776cd2fdb3996cbd900d6/sparql/sparql11/subquery/manifest.ttl#L39).

According to the expected results (`sq02.srx`), `sq02.rq` should return one solution. Why is this the case?
Since the subquery projects `?g`, whose bindings do not match with any of the named graphs' IRIs, shouldn't the expected results be equal to the empty result set?
~~FYI, Apache Jena 5.2.0 does not return any results for this query.~~

Thank you in advance.

**Comment by nkaralis** [comment]
Thank you for the quick response.

I mistook the object of the statement `<rdf:Description rdf:about="http://www.example.org/instance#c"> <ex:p rdf:resource=""/>` (`sq01.rdf`) to be an empty string literal.

However, according to the expected results, `?g` is supposed to be matched only with the object of the above statement. It is not matched with the graph's other statement.

**Comment by rubensworks** [comment]
The `rdf:resource=""` refers to the baseIRI, which correspond to the URL of the document itself.
For example, parsing the URL `https://raw.githubusercontent.com/w3c/rdf-tests/12a81bbafc522850ae5776cd2fdb3996cbd900d6/sparql/sparql11/subquery/sq01.rdf`
should get you as output:
```
<http://www.example.org/instance#a> <http://www.example.org/schema#p> <http://www.example.org/instance#b>.
<http://www.example.org/instance#c> <http://www.example.org/schema#p> <https://raw.githubusercontent.com/w3c/rdf-tests/12a81bbafc522850ae5776cd2fdb3996cbd900d6/sparql/sparql11/subquery/sq01.rdf>
```

Since the graph data is placed in the named graph with identifier `https://raw.githubusercontent.com/w3c/rdf-tests/12a81bbafc522850ae5776cd2fdb3996cbd900d6/sparql/sparql11/subquery/sq01.rdf`, the query will therefore have one result.

**Comment by nkaralis** [comment]
Thank you for the detailed explanation.
