### ISSUE TITLE
File delete-insert-07b.ru is tagged as bad but looks good to me

### ISSUE THREAD

**Issue by tonicebrian** [w3c/rdf-tests#60]
In https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/delete-insert/manifest.ttl#L161-L167 the test is marked as NegativeSyntax. I've implemented a grammar that correctly parses it and thus fails my tests expecting an exception. 

So my questions is, is it correctly flagged as Negative ? And if so, where is the problem of that query and where the grammar should fail to parse?

**Comment by afs** [comment]
It's an error because it violates one of the additional rules. There are a number of cases where things are illegal even if the grammar rules don't preclude them. Here, blank nodes in the DELETE clause (which are meaningless - they can't be in the data and they are not unnamed variables).

https://www.w3.org/TR/sparql11-query/#grammarBNodes

Writing a grammar that had a different set of rules for each variations would be burdensome on the parser writer. The grammar could easily be 2 or more times larger with a lot of nearly identical repetition if each case is written out - you have to write out rules again all the way up through for all the places it gets used. Instead, it is done with the same grammar rules with addition restrictions as a second pass over the parse tree. In practical term, these can be implemented taking note of context while parsing.

**Comment by tonicebrian** [comment]
Thanks for the response. I wasn't aware of that note of the grammar. I've solved the issue by adding a semantic action that whenever I enter a block of one of those DELETEs blanks fail to parse. 

But then and as a matter of completeness, I think you could do something on your side to make it clear, becase either:

- The grammar as published in https://www.w3.org/TR/sparql11-query/#sparqlGrammar is bad defined since that file correctly parses according to rule https://www.w3.org/TR/sparql11-query/#rModify is valid and thus the grammar would require different branches according to whether a blank is defined for those rules.
- The tagging in `manifest.ttl` stating that the example is of type `mf:NegativeSyntaxTest11` should be changed to `mf:InvalidSparqlTest11` or something similar since the syntax is right but it is when interpreting it when it is invalid. In fact something similar happened with another test after fixing this one. The file `aggregates/agg12.rq` is also syntactically valid but when interpreted as Sparql is invalid. 

Just my 2 cents to improve the system. Implementing a complete parser is out of scope for me since I just want a shallow checker but right now I cannot use the Negative examples set because they involve semantic actions.

**Comment by afs** [comment]
@tonicebrian 
Thanks - feedback noted.

**Comment by ericprud** [comment]
@tonicebrian , as you noted, you fixed it with a semantic action. I think it's sensible to mark the test as a `NegativeSyntaxTest11` so you don't have to [add another type](https://github.com/w3c/rdf-tests/tree/gh-pages/sparql11#manifest-structure).

In ShEx, we wrap all grammar rules (BNF or English) into [negativeSyntax](https://github.com/shexSpec/shexTest/tree/master/negativeSyntax) and reserve [negativeStructure](https://github.com/shexSpec/shexTest/tree/master/negativeStructure) for static analysis failures like bad references to shapes. If SPARQL-next adds named patterns, it would make sense to do the same.
