### ISSUE TITLE
Possible contradiction between USING semantics in spec and tests

### ISSUE THREAD

**Issue by rubensworks** [w3c/rdf-tests#72]
This issue is regarding a (possible) contradiction in the semantics of `USING` between the spec and the test suite in update queries:

* http://www.w3.org/2009/sparql/docs/tests/data-sparql11/delete/manifest#dawg-delete-using-02a
* http://www.w3.org/2009/sparql/docs/tests/data-sparql11/delete/manifest#dawg-delete-using-06a

These tests check that "modifying the desired graph making sure the GRAPH clause does not override the USING clause".

As defined in [the spec](https://www.w3.org/TR/sparql11-update/#delete_insert_clause):

> The USING and USING NAMED clauses affect the RDF Dataset used while evaluating the WHERE clause. This describes a dataset in the same way as FROM and FROM NAMED clauses describe RDF Datasets in the SPARQL 1.1 Query Language. The keyword USING instead of FROM in update requests is to avoid possible ambiguities which could arise from writing "DELETE FROM". That is, the GroupGraphPattern in the WHERE clause will be matched against the dataset described by explicit USING or USING NAMED clauses, if specified, and against the Graph Store otherwise.

This seems to imply that implementations may decide to internally translate `USING` to `FROM`.

However, as far as I can see, the SPARQL query spec makes no explicit mentions stating that the `GRAPH` clause can not override the `FROM` clause. Even more, the examples even seem to contradict this.

-----

To make this issue more concrete, let me give a brief example.
If I understand the SPARQL query spec correctly, the following query should apply to triples in `ex:g2`, and `GRAPH` therefore overrides `FROM` (in the scope of the `GRAPH` close).
However, the tests mentioned above seem to imply that (due to the `USING` semantics), this is in fact not the case, and this query should in fact apply to triples in `ex:g1` (ignoring the `GRAPH` clause).

```sparql
SELECT  *
FROM <ex:g1>
WHERE   {
  GRAPH <ex:g2> {
    ?s ?p ?o
  }
}
```

So my questions are: Are these two spec tests incorrect, as they suggest a different meaning of `USING` and `FROM`?
Or are these tests correct, and do `USING` and `FROM` really have a different meaning?
Or is my understanding of `FROM` wrong?

Related to https://github.com/joachimvh/SPARQLAlgebra.js/issues/77

**Comment by afs** [comment]
This is complicated - this is how I see the specs in detail to see if we read them the same way.

If FROM/FROM NAMED is used, then that describes a dataset. So in:

```sparql
SELECT  *
FROM <ex:g1>
WHERE 
```
and the dataset for the query matching contains a default graph with the contents of `ex:g1` and no named graphs. `ex:g1` is taken from somewhere - it can be some persistent dataset (a common feature of implementations).

If that is so then: `delete-using-02.ru`:

`USING` only applies to matching, and does not change the underlying dataset being updated.  USING/USING NAMED create       a view.  FORM/FROM NAMED also create a view if we assume the graph they identify are taken from some dataset.

```sparql
DELETE 
{
  ?s ?p ?o .
}
USING <http://example.org/g3>
WHERE 
{
  GRAPH <http://example.org/g2> { :a foaf:knows ?s .
                                  ?s ?p ?o }
}
```
and matching the DELETE-USING part will not match because there is no graph `http://example.org/g2` in the view dataset used - it only has  default graph (contents `http://example.org/g3`). This is like FROM/FROM NAMED behaviour.

Therefore the update has no effect - the default graph, and graphs http://example.org/g3 and http://example.org/g2 are unchanged. Files "pre" and "post" in the test ("delete-pre-01.ttl" and "delete-post-01f.ttl", "delete-pre-02.ttl" and "delete-post-02f.ttl",  "delete-pre-03.ttl" and "delete-post-03f.ttl") are the same.

Are we talking about the same thing here?

"matched _against_ the dataset" => "matched against _a_ dataset" would be a little clearer.

**Comment by rubensworks** [comment]
Thanks for the clarification @afs!

From your explanation, it became clear to me that I misunderstood FROM/FROM NAMED.
I previously thought that when using FROM without a FROM NAMED, still enables querying over other named graphs using GRAPH.
But from your comment, it became clear to me that when using FROM without FROM NAMED, the query dataset becomes a view that _only_ includes the (target) default graph, without any other named graphs.
(I thought our implementation of FROM/FROM NAMED was correct, as it passed all query tests, but apparently this detail is not covered in the query test suite)

Based on this, it seems clear to me that there is no difference between USING and FROM, so I'm closing this issue.
